### ISSUE TITLE
yarn install fails on Windows 10 dev machine

### ISSUE THREAD

**Issue by macjuan** [vaadin/vaadin-connect#150]
PS C:\Users\juha\Sorsat\vaadin-connect> yarn install
yarn install v1.12.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-7ae2543a-4fcd-4a79-a397-740229065f0b > @vaadin/connect > sinon-chai@3.3.0" has unmet peer dependency "chai@^4.0.0".
warning "workspace-aggregator-7ae2543a-4fcd-4a79-a397-740229065f0b > vaadin-connect-demo > polyserve > polymer-project-config@4.0.2" has unmet peer dependency "polymer-analyzer@^3.0.1".
[4/4] Building fresh packages...
[1/2] ⠠ iltorb
error C:\Users\juha\Sorsat\vaadin-connect\frontend\connect\node_modules\iltorb: Command failed.
Exit code: 1
Command: detect-libc prebuild-install || node-gyp rebuild
Arguments:
Directory: C:\Users\juha\Sorsat\vaadin-connect\frontend\connect\node_modules\iltorb
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.12.0 runtime=node arch=x64 platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.12.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\juha\scoop\shims\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\juha\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\Users\\juha\\Sorsat\\vaadin-connect\\frontend\\connect\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\juha\Sorsat\vaadin-connect\frontend\connect\node_modules\iltorb
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by macjuan** [comment]
That solved the issue. Closing.
