### ISSUE TITLE
Vaadin 12 - yarn throws E2BIG (ERROR_META_EXPANSION_TOO_LONG)

### ISSUE THREAD

**Issue by Duncol** [vaadin/vaadin-connect#333]
Hi everyone, after upgrading Vaadin 10 ino Vaadin 12 I've encountered problem mentioned above.
Thing is happening regarding Jenkins pipeline, but this seems like an internal Vaadin phase. I've found out that it might be caused by NOTICE file and 'noticeText' in package.json, however it seems that yarn guys fixed this already https://github.com/yarnpkg/yarn/pull/5666 .

Yarn version: 
  1.6.0

Node version: 
  8.11.1

Platform: 
  linux x64

```
Trace: 
  Error: /data/jenkinspl/workspace/my-project-branch/target/node_modules/iltorb: spawn E2BIG
      at _errnoException (util.js:1022:11)
      at ChildProcess.spawn (internal/child_process.js:323:11)
      at Object.exports.spawn (child_process.js:502:9)
      at /data/jenkinspl/workspace/my-project-branche/target/node/yarn/dist/lib/cli.js:30262:24
      at new Promise (<anonymous>)
      at new F (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:23469:28)
      at /data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:30261:12
      at run (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:41698:7)
      at BlockingQueue.maybePushConcurrencyQueue (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:41713:7)
      at BlockingQueue.shift (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:41708:10)
```

**Comment by vlukashov** [comment]
Hi @Duncol, this is a repo for issues related to a Vaadin Labs project called [Vaadin Connect](https://vaadin.com/labs/vaadin-connect). The issue you are reporting seems to be about the Vaadin Platrorm. Are you sure this is the right place for it?

To get the relevant people see it, you would probably want to move the issue to a better place (e.g. the vaadin/platform or vaadin/flow repo).

**Comment by Duncol** [comment]
Oh sorry, I've entered this ticket from other yarn issue context I've found here. Are you in power of moving such things, or shall I delete this an create a new one in Vaadin Platform?

**Comment by SomeoneToIgnore** [comment]
I can handle the move, no worries.
